version: '3'
name: task_core
services:
  azuresqledgedb:
    container_name: azuresqledgedb
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Password.1
    ports:
      - "1433:1433"
    cap_add:
      - SYS_PTRACE
    restart: always
    volumes:
      - azuresqledgedb-data:/var/opt/mssql

  elasticsearch:
    container_name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.7.1"
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: "docker.elastic.co/kibana/kibana:8.7.1"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
        
volumes:
  azuresqledgedb-data:
  elasticsearch-data: